"""

"""

PREFIX = "_pyprofiler."

# init
PROFILING_ADDED = PREFIX + "__PROFILING_ADDED__"

# runtime
IGNORE = PREFIX + "__IGNORE__"
STOP_AFTER = PREFIX + "__STOP_AFTER__"
STOP_BEFORE = PREFIX + "__STOP_BEFORE__"
SAVE = PREFIX + "__SAVE__"
